In [1]:
import sys
from pyecharts import options as opts
sys.path.append("..") 
from imp import reload
from src.stock import Stock

In [2]:
stock = Stock()

/Users/david/anaconda3/lib/python3.6/site-packages/tushare/util/upass.py:28: FutureWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  return str(df.ix[0]['token'])

In [3]:
stock.get_hs_300()

          index_code   con_code trade_date  weight
con_code
002773.SZ  399300.SZ  002773.SZ   20191008  0.0702
002714.SZ  399300.SZ  002714.SZ   20191008  0.5026
601238.SH  399300.SZ  601238.SH   20191008  0.0904
603288.SH  399300.SZ  603288.SH   20191008  0.7087
603993.SH  399300.SZ  603993.SH   20191008  0.2045
...              ...        ...        ...     ...
000333.SZ  399300.SZ  000333.SZ   20191008  2.0500
601808.SH  399300.SZ  601808.SH   20191008  0.0588
601939.SH  399300.SZ  601939.SH   20191008  0.3812
002179.SZ  399300.SZ  002179.SZ   20191008  0.1636
601169.SH  399300.SZ  601169.SH   20191008  0.6396

[300 rows x 4 columns]

In [4]:
stock.get_zz_500()

          index_code   con_code trade_date  weight
con_code
002390.SZ  000905.SH  002390.SZ   20190930   0.145
002387.SZ  000905.SH  002387.SZ   20190930   0.365
002385.SZ  000905.SH  002385.SZ   20190930   0.305
002384.SZ  000905.SH  002384.SZ   20190930   0.498
002382.SZ  000905.SH  002382.SZ   20190930   0.097
...              ...        ...        ...     ...
600729.SH  000905.SH  600729.SH   20190930   0.183
600718.SH  000905.SH  600718.SH   20190930   0.250
600717.SH  000905.SH  600717.SH   20190930   0.162
600707.SH  000905.SH  600707.SH   20190930   0.085
600699.SH  000905.SH  600699.SH   20190930   0.354

[500 rows x 4 columns]

In [5]:
stock.get_sz_50()

          index_code   con_code trade_date  weight
con_code
601668.SH  000016.SH  601668.SH   20190930   2.045
601186.SH  000016.SH  601186.SH   20190930   0.781
601211.SH  000016.SH  601211.SH   20190930   1.421
601229.SH  000016.SH  601229.SH   20190930   1.191
601288.SH  000016.SH  601288.SH   20190930   2.378
601318.SH  000016.SH  601318.SH   20190930  16.915
601319.SH  000016.SH  601319.SH   20190930   0.164
601328.SH  000016.SH  601328.SH   20190930   2.686
601336.SH  000016.SH  601336.SH   20190930   0.728
601390.SH  000016.SH  601390.SH   20190930   0.877
601398.SH  000016.SH  601398.SH   20190930   2.140
601601.SH  000016.SH  601601.SH   20190930   1.966
601628.SH  000016.SH  601628.SH   20190930   0.821
601166.SH  000016.SH  601166.SH   20190930   4.573
601688.SH  000016.SH  601688.SH   20190930   1.247
601766.SH  000016.SH  601766.SH   20190930   1.278
601800.SH  000016.SH  601800.SH   20190930   0.426
601818.SH  000016.SH  601818.SH   20190930   1.126
601857.SH  000016.SH  601857.SH   20190930   0.899
601888.SH  000016.SH  601888.SH   20190930   1.630
601939.SH  000016.SH  601939.SH   20190930   0.842
601988.SH  000016.SH  601988.SH   20190930   1.354
601989.SH  000016.SH  601989.SH   20190930   0.905
603259.SH  000016.SH  603259.SH   20190930   0.228
603993.SH  000016.SH  603993.SH   20190930   0.461
600309.SH  000016.SH  600309.SH   20190930   1.243
600016.SH  000016.SH  600016.SH   20190930   2.681
600019.SH  000016.SH  600019.SH   20190930   0.945
600028.SH  000016.SH  600028.SH   20190930   1.205
600029.SH  000016.SH  600029.SH   20190930   0.409
600030.SH  000016.SH  600030.SH   20190930   3.174
600031.SH  000016.SH  600031.SH   20190930   1.502
600036.SH  000016.SH  600036.SH   20190930   6.430
600048.SH  000016.SH  600048.SH   20190930   1.831
600050.SH  000016.SH  600050.SH   20190930   1.004
600104.SH  000016.SH  600104.SH   20190930   1.495
600196.SH  000016.SH  600196.SH   20190930   0.456
600276.SH  000016.SH  600276.SH   20190930   4.481
600000.SH  000016.SH  600000.SH   20190930   2.494
600340.SH  000016.SH  600340.SH   20190930   0.872
600519.SH  000016.SH  600519.SH   20190930  10.367
600585.SH  000016.SH  600585.SH   20190930   1.483
600690.SH  000016.SH  600690.SH   20190930   1.004
600703.SH  000016.SH  600703.SH   20190930   0.618
600837.SH  000016.SH  600837.SH   20190930   2.076
600887.SH  000016.SH  600887.SH   20190930   3.120
601066.SH  000016.SH  601066.SH   20190930   0.179
601088.SH  000016.SH  601088.SH   20190930   1.111
601111.SH  000016.SH  601111.SH   20190930   0.429
601138.SH  000016.SH  601138.SH   20190930   0.308